ModName="TrainsWhistle"
trainWhistleEquipment="trainWhistleEquipment"
trainWhistleEquipmentGrid="train-Whistle-Equipment-Grid"
technologyName="trainWhistleTech"
onTrainWhistled="on_train_whistled"
trainStopGhost="trainStopGhost"