name: Auto publish

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  setup:
    runs-on: ubuntu-latest
    #outputs:
    #  matrix: ${{ steps.matrix.outputs.value }}
    steps:
      #- uses: nearform-actions/github-action-check-linked-issues@v1
      #  id: get-linked-issues
      - name: download list issues as json
        #env:
        #  LIST_ISSUES: ${{ steps.get-linked-issues.outputs.issues }}
        run: |
          echo ${{ toJson(env) }}
          
    
  ## build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository and submodules
  #     uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #   - name: get mod_version
  #     id: mod_version
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'version'
  #   - name: get factorio_version
  #     id: factorio_version
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'factorio_version'
  #   - name: get mod name
  #     id: mod_name
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'name'
  #   - name: Zip mod
  #     run: bash ./.scripts/zip_mod.sh
  #   - name: Upload the mod on mods.factorio.com
  #     env:
  #       FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
  #     run: bash ./.scripts/upload.sh
  #   - uses: marvinpinto/action-automatic-releases@latest
  #     id: aar
  #     with:
  #       automatic_release_tag: "${{steps.mod_version.outputs.prop}}"
  #       title: "For factorio ${{steps.factorio_version.outputs.prop}}"
  #       repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #       prerelease: false
  #       files: |
  #         ./${{steps.mod_name.outputs.prop}}_${{steps.version.outputs.prop}}.zip