name: Auto publish

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      VERSION_LEVEL: 2
    steps:
    - if: contains(github.event.pull_request.labels.*.name, 'minor')
      env: 
        VERSION_LEVEL: 0
      uses: actions/checkout@v3
    - if: contains(github.event.pull_request.labels.*.name, 'major')
      env: 
        VERSION_LEVEL: 0
      uses: actions/checkout@v3
    - name: get data
      env:
        SOURCE_BRANCH: ${{ github.head_ref}}	
        PULL_REQUEST_DESCRIPTION: ${{ github.event.pull_request.body }}
      run: echo $VERSION_LEVEL
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository and submodules
  #     uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #   - name: get mod_version
  #     id: mod_version
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'version'
  #   - name: get factorio_version
  #     id: factorio_version
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'factorio_version'
  #   - name: get mod name
  #     id: mod_name
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'name'
  #   - name: Zip mod
  #     run: bash ./.scripts/zip_mod.sh
  #   - name: Upload the mod on mods.factorio.com
  #     env:
  #       FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
  #     run: bash ./.scripts/upload.sh
  #   - uses: marvinpinto/action-automatic-releases@latest
  #     id: aar
  #     with:
  #       automatic_release_tag: "${{steps.mod_version.outputs.prop}}"
  #       title: "For factorio ${{steps.factorio_version.outputs.prop}}"
  #       repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #       prerelease: false
  #       files: |
  #         ./${{steps.mod_name.outputs.prop}}_${{steps.version.outputs.prop}}.zip