name: Deploy on aws eb
on:
  workflow_dispatch:
    inputs:
      title:
            description: 'Title of the mod'     
            required: true
      description:
            description: 'Description of the mod'     
            required: true

jobs:
  Update_To_Factorio:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'
      - run: pip install -r ".scripts/requirements.txt"
      - name: Create new mod
              env:
                OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
                FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
                MOD_AUTHOR: ${{ env.MOD_AUTHOR }}
                TITLE: ${{github.input.event.title}}
                DESCRIPTION: ${{github.input.event.description}}
              run: python .scripts/DuplicateFactorioModel.py