name: Create factorio mod
on:
  workflow_dispatch:
    inputs:
      title:
            description: 'Title of the mod'     
            required: true
      description:
            description: 'Description of the mod'     
            required: true

jobs:
  Create_Factorio_Mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'
      - run: pip install -r ".scripts/requirements.txt"
      - name: Create new mod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
          MOD_AUTHOR: ${{ env.MOD_AUTHOR }}
          TITLE: ${{github.event.inputs.title}}
          DESCRIPTION: ${{github.event.inputs.description}}
        run: python .scripts/DuplicateFactorioModel.py