# This is a basic workflow to help you get started with Actions

name: Deploy
# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      version_level:
        description: 'version level (0:Major, 1:minor, 2:bugfix) - default 2'
        required: false
        type: string
        default: "2"
      changelog:
        description: "Changelog"
        required: true
        type: string
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: list mods changed
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          LIST_MOD_CHANGES: ()
        run: |
          for file in "$ALL_CHANGED_FILES"; do
            root=$(echo "$file" | cut -d "/" -f2)
            if !([[ ${array[@]} =~ "\<$root\>" ]]); then
              LIST_MOD_CHANGES+=($root)
            fi
          done
      - name: Update info.json
        run: |
          for file in "$LIST_MOD_CHANGES"; do
            sh ${GITHUB_WORKSPACE}/.github/workflows/updateInfoJson.sh $file ${{ inputs.version_level }}
          done
      - name: Update changelog
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
