# This is a basic workflow to help you get started with Actions

name: Deploy
# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      is_major:
        description: 'Is Major'
        required: false
        type: boolean
        default: false
      changelog:
        description: "Changelog"
        required: true
        type: string
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Update info.json
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Update changelog
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
