name: Auto publish

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  Update_To_Factorio:
    uses: Hermios/Factorio-model/.github/workflows/PublishInFactorio.yml@main
    secrets: inherit