name: Auto publish

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: ".scripts/requirements.txt"
      - name: Run Create Release
        env:
          PULL_REQUEST: ${{ toJson(github.event.pull_request) }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
        run: python .scripts/CreateRelease.py
          
    
  ## build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository and submodules
  #     uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #   - name: get mod_version
  #     id: mod_version
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'version'
  #   - name: get factorio_version
  #     id: factorio_version
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'factorio_version'
  #   - name: get mod name
  #     id: mod_name
  #     uses: notiz-dev/github-action-json-property@release
  #     with:
  #       path: 'info.json'
  #       prop_path: 'name'
  #   - name: Zip mod
  #     run: bash ./.scripts/zip_mod.sh
  #   - name: Upload the mod on mods.factorio.com
  #     env:
  #       FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
  #     run: bash ./.scripts/upload.sh
  #   - uses: marvinpinto/action-automatic-releases@latest
  #     id: aar
  #     with:
  #       automatic_release_tag: "${{steps.mod_version.outputs.prop}}"
  #       title: "For factorio ${{steps.factorio_version.outputs.prop}}"
  #       repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #       prerelease: false
  #       files: |
  #         ./${{steps.mod_name.outputs.prop}}_${{steps.version.outputs.prop}}.zip